# goal in same frame as measured position.
int32 target_index # index of item within mission
float64 target_x # meters
float64 target_y # meters
float64 acceptance_radius # meters
bool stop_at_target
---
# result
float64 distance_remaining # meters
---
# feedback
float64 distance_remaining # meters